name: opaku
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.1
  google_fonts: ^2.1.0
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  collection: ^1.15.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

